#wallpaper {
#	monitor = eDP-1
#	path = /home/jefferson/Imagens/selectedWallp/dark-cottage.jpeg
#	fit_mode = cover
#}

#wallpaper {
#	monitor = HDMI-A-1
#	path = /home/jefferson/Imagens/selectedWallp/dark-cottage.jpeg
#	fit_mode = cover
#}

#splash = false


#  /home/jefferson/Imagens/Wallpapers/wallhaven-zpx3xw.png
