foreground         #c2c3c5
background         #0b0f1a
background_opacity 1.0
cursor             #c2c3c5

active_tab_foreground     #0b0f1a
active_tab_background     #c2c3c5
inactive_tab_foreground   #c2c3c5
inactive_tab_background   #0b0f1a

active_border_color   #c2c3c5
inactive_border_color #0b0f1a
bell_border_color     #933b3d

color0       #0b0f1a
color8       #5a606f
color1       #933b3d
color9       #C44F52
color2       #013f69
color10      #02548D
color3       #044874
color11      #06609B
color4       #133a7b
color12      #1A4EA5
color5       #005481
color13      #0070AD
color6       #0f7296
color14      #1498C8
color7       #8e9299
color15      #c2c3c5
