include ~/.config/kitty/themes/mocha.conf

font_family	Geist Nerd Font Mono
font_size	12.0
bold_font        auto
italic_font      auto
bold_italic_font auto

shell	zsh

# Main 0.8
background_opacity	0.8
window_padding_width 7

cursor_shape	beam
cursor_shape_unfocused unchanged

url_style	curly

confirm_os_window_close	0
sync_to_monitor	no


shell_integration no-rc
startup_session none

# TabBar like NVim

#tab_bar_min_tabs            1
#tab_bar_edge                bottom
#tab_bar_style               powerline
#tab_powerline_style         slanted
#tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}


#=================================#
# 			 MY BINDS
#=================================#

map super+c copy_to_clipboard
map super+v paste_from_clipboard


#=================================#


